Repository 2022Allie/ChocokCake_Backend, pull requests merged in 2022-07, with the labels that each got.

#22 16 Cake Candle Mapping
  src/main/java/com/example/chocokcake/entity/Cake.java
  src/main/java/com/example/chocokcake/entity/Candle.java
  src/main/java/com/example/chocokcake/entity/User.java
Labels: enhancement

#25 24 Login API
  src/main/java/com/example/chocokcake/controller/CakeController.java
  src/main/java/com/example/chocokcake/controller/UserController.java
  src/main/java/com/example/chocokcake/controller/dto/ErrorResponse.java
  src/main/java/com/example/chocokcake/controller/dto/LoginRequest.java
  src/main/java/com/example/chocokcake/controller/dto/MessageResponse.java
  src/main/java/com/example/chocokcake/controller/dto/TokenResponse.java
  src/main/java/com/example/chocokcake/controller/dto/UserRequest.java
  src/main/java/com/example/chocokcake/entity/repository/CakeRepository.java
  src/main/java/com/example/chocokcake/entity/repository/UserRepository.java
  src/main/java/com/example/chocokcake/exception/ErrorCode.java
  src/main/java/com/example/chocokcake/exception/ExceptionHandlerFilter.java
  src/main/java/com/example/chocokcake/security/auth/AuthDetailsService.java
  src/main/java/com/example/chocokcake/security/auth/AuthenticationFacade.java
  src/main/java/com/example/chocokcake/service/CakeService.java
  src/main/java/com/example/chocokcake/service/UserService.java
Labels: enhancement

#32 31 Update sign up
  src/main/java/com/example/chocokcake/controller/dto/UserRequest.java
  src/main/java/com/example/chocokcake/security/auth/AuthenticationFacade.java
  src/main/java/com/example/chocokcake/service/UserService.java
Labels: documentation

#33 20 Get My Cake Information API
  src/main/java/com/example/chocokcake/controller/CakeController.java
  src/main/java/com/example/chocokcake/controller/dto/ReadUserCakeResponse.java
  src/main/java/com/example/chocokcake/entity/repository/CakeRepository.java
  src/main/java/com/example/chocokcake/service/CakeService.java
Labels: enhancement

#34 27 Get Cake Information API
  src/main/java/com/example/chocokcake/controller/CakeController.java
  src/main/java/com/example/chocokcake/controller/dto/ReadCakeDetailsResponse.java
  src/main/java/com/example/chocokcake/exception/ErrorCode.java
  src/main/java/com/example/chocokcake/service/CakeService.java
Labels: enhancement

#36 26 Create UnAuthorization Exception Handler
  src/main/java/com/example/chocokcake/exception/ErrorCode.java
  src/main/java/com/example/chocokcake/exception/ExceptionHandlerFilter.java
  src/main/java/com/example/chocokcake/exception/GlobalExceptionHandler.java
Labels: enhancement

#37 Create writing candle letter
  src/main/java/com/example/chocokcake/controller/CakeController.java
  src/main/java/com/example/chocokcake/controller/CandleController.java
  src/main/java/com/example/chocokcake/controller/dto/LetterRequest.java
  src/main/java/com/example/chocokcake/controller/dto/UserRequest.java
  src/main/java/com/example/chocokcake/service/CandleService.java
Labels: enhancement

#40 38 Create Withdrawal
  src/main/java/com/example/chocokcake/controller/CakeController.java
  src/main/java/com/example/chocokcake/controller/CandleController.java
  src/main/java/com/example/chocokcake/controller/UserController.java
  src/main/java/com/example/chocokcake/service/UserService.java
Labels: enhancement

#39 30 Get Candle Letter Information API
  src/main/java/com/example/chocokcake/controller/CandleController.java
  src/main/java/com/example/chocokcake/controller/dto/LetterResponse.java
  src/main/java/com/example/chocokcake/exception/ErrorCode.java
  src/main/java/com/example/chocokcake/service/CandleService.java
Labels: enhancement

#42 41 Update Errorcode
  src/main/java/com/example/chocokcake/exception/ErrorCode.java
Labels: documentation

#51 45 Update withdrawal
  src/main/java/com/example/chocokcake/entity/repository/UserRepository.java
  src/main/java/com/example/chocokcake/service/UserService.java
Labels: bug, documentation

#58 49 Update GET letter
  src/main/java/com/example/chocokcake/controller/CandleController.java
  src/main/java/com/example/chocokcake/service/CandleService.java
Labels: bug, documentation

#60 57 Update getCake'sCandleAll
  src/main/java/com/example/chocokcake/service/CandleService.java
Labels: bug, documentation

#61 50 Update create cake
  src/main/java/com/example/chocokcake/exception/ErrorCode.java
  src/main/java/com/example/chocokcake/exception/ExceptionHandlerFilter.java
  src/main/java/com/example/chocokcake/exception/GlobalExceptionHandler.java
  src/main/java/com/example/chocokcake/exception/UnAuthorizedTokenException.java
  src/main/java/com/example/chocokcake/exception/costomException/BaseException.java
  src/main/java/com/example/chocokcake/exception/costomException/UnAuthorizedTokenException.java
  src/main/java/com/example/chocokcake/security/auth/AuthenticationFacade.java
  src/main/java/com/example/chocokcake/service/CakeService.java
  src/main/java/com/example/chocokcake/service/CandleService.java
  src/main/java/com/example/chocokcake/service/UserService.java
Labels: bug, documentation

#62 59 Update withdrawal
  src/main/java/com/example/chocokcake/entity/Cake.java
  src/main/java/com/example/chocokcake/entity/User.java
  src/main/java/com/example/chocokcake/service/UserService.java
Labels: bug, documentation

#66 65 Create Token Exception
  src/main/java/com/example/chocokcake/exception/ErrorCode.java
  src/main/java/com/example/chocokcake/exception/GlobalExceptionHandler.java
Labels: enhancement

#68 67 Update create cake
  src/main/java/com/example/chocokcake/entity/Cake.java
  src/main/java/com/example/chocokcake/entity/User.java
  src/main/java/com/example/chocokcake/service/CakeService.java
  src/main/java/com/example/chocokcake/service/CandleService.java
Labels: documentation, enhancement

#69 67 Update create cake
  src/main/java/com/example/chocokcake/service/CakeService.java
Labels: documentation, enhancement

#76 75 Create get member
  src/main/java/com/example/chocokcake/domain/controller/CakeController.java
  src/main/java/com/example/chocokcake/domain/controller/UserController.java
  src/main/java/com/example/chocokcake/domain/controller/dto/UserInfoResponse.java
  src/main/java/com/example/chocokcake/domain/service/UserService.java
Labels: enhancement

#78 75 Create get member
  src/main/java/com/example/chocokcake/domain/controller/CakeController.java
  src/main/java/com/example/chocokcake/domain/controller/CandleController.java
  src/main/java/com/example/chocokcake/domain/controller/UserController.java
  src/main/java/com/example/chocokcake/domain/controller/dto/request/AccountIdRequest.java
  src/main/java/com/example/chocokcake/domain/controller/dto/request/LetterRequest.java
  src/main/java/com/example/chocokcake/domain/controller/dto/request/LoginRequest.java
  src/main/java/com/example/chocokcake/domain/controller/dto/request/ThemeRequest.java
  src/main/java/com/example/chocokcake/domain/controller/dto/request/UserRequest.java
  src/main/java/com/example/chocokcake/domain/controller/dto/response/CandleListResponse.java
  src/main/java/com/example/chocokcake/domain/controller/dto/response/CandleResponse.java
  src/main/java/com/example/chocokcake/domain/controller/dto/response/LetterResponse.java
  src/main/java/com/example/chocokcake/domain/controller/dto/response/MessageResponse.java
  src/main/java/com/example/chocokcake/domain/controller/dto/response/ReadCakeDetailsResponse.java
  src/main/java/com/example/chocokcake/domain/controller/dto/response/ReadUserCakeListResponse.java
  src/main/java/com/example/chocokcake/domain/controller/dto/response/ReadUserCakeResponse.java
  src/main/java/com/example/chocokcake/domain/controller/dto/response/TokenResponse.java
  src/main/java/com/example/chocokcake/domain/controller/dto/response/UserInfoResponse.java
  src/main/java/com/example/chocokcake/domain/entity/candle/CandleRepository.java
  src/main/java/com/example/chocokcake/domain/service/CakeService.java
  src/main/java/com/example/chocokcake/domain/service/CandleService.java
  src/main/java/com/example/chocokcake/domain/service/UserService.java
  src/main/java/com/example/chocokcake/global/error/ErrorCode.java
  src/main/java/com/example/chocokcake/global/error/ErrorResponse.java
  src/main/java/com/example/chocokcake/global/error/ExceptionHandlerFilter.java
  src/main/java/com/example/chocokcake/global/error/GlobalExceptionHandler.java
  src/main/java/com/example/chocokcake/global/error/exception/AlreadyBirthdayLaterException.java
  src/main/java/com/example/chocokcake/global/error/exception/AlreadyExistCakeException.java
  src/main/java/com/example/chocokcake/global/error/exception/BaseException.java
  src/main/java/com/example/chocokcake/global/error/exception/DuplicateMemberException.java
  src/main/java/com/example/chocokcake/global/error/exception/ForbiddenException.java
  src/main/java/com/example/chocokcake/global/error/exception/NotFoundCakeException.java
  src/main/java/com/example/chocokcake/global/error/exception/NotFoundCandleException.java
  src/main/java/com/example/chocokcake/global/error/exception/NotFoundUserException.java
  src/main/java/com/example/chocokcake/global/error/exception/NotYetBirthdayException.java
  src/main/java/com/example/chocokcake/global/error/exception/PasswordNotMatchedException.java
  src/main/java/com/example/chocokcake/global/error/exception/UnAuthorizedTokenException.java
  src/main/java/com/example/chocokcake/global/error/exception/UnAuthorizedTokenFilterException.java
  src/main/java/com/example/chocokcake/global/exception/costomException/UnAuthorizedTokenException.java
  src/main/java/com/example/chocokcake/global/security/JwtConfigurer.java
  src/main/java/com/example/chocokcake/global/security/SecurityConfig.java
  src/main/java/com/example/chocokcake/global/security/auth/AuthenticationFacade.java
Labels: documentation

#80 79 Update get-candle-list
  src/main/java/com/example/chocokcake/domain/service/CandleService.java
Labels: documentation

#81 79 Update get-candle-list
  src/main/java/com/example/chocokcake/domain/service/CandleService.java
Labels: documentation

#82 79 Update get-candle-list
  src/main/java/com/example/chocokcake/domain/service/CakeService.java
  src/main/java/com/example/chocokcake/domain/service/CandleService.java
  src/main/java/com/example/chocokcake/domain/service/UserService.java
Labels: documentation

#83 79 Update get-candle-list
  src/main/java/com/example/chocokcake/domain/service/CandleService.java
Labels: documentation

#84 79 Update get-candle-list
  src/main/java/com/example/chocokcake/domain/service/CandleService.java
Labels: documentation
